- name: put timer code
  template:
    src: monitor.sh.j2
    dest: /home/ubuntu/monitor.sh
    mode: "0755"

- name: exec monitor sh
  shell: /home/ubuntu/monitor.sh 2> /tmp/monitor_error.log
  async: 5
  poll: 0

- name: start containers
  docker_container:
    name: "{{ item.NAME }}"
    image: siit_gobgpd
    state: started
    restart: yes
    recreate: yes
    auto_remove: yes
    networks:
      - ipv6_address: "{{ POD_NETWORK }}{{ item.ROUTER_ID }}"
        name: service_net
    env:
      ROUTER_ID: "{{ item.ROUTER_ID }}"
      AS_NUMBER: "{{ AS_NUMBER }} "
      IS_RR: "false"
      IS_INJECTOR: "false"
      RR_ADDRESS1: "{{ RR_ADDRESS1 }}"
      RR_ADDRESS2: "{{ RR_ADDRESS2 }}"
      TRANSLATION_PREFIX: "{{ TRANSLATION_PREFIX }}"
  loop: "{{ CONTAINERS }}"
  when: not STOPPED

- name: remove container
  docker_container:
    name: "{{ item.NAME }}"
    image: siit_gobgpd
    state: absent
    auto_remove: yes
    networks:
      - ipv6_address: "{{ POD_NETWORK }}{{ item.ROUTER_ID }}"
        name: service_net
    env:
      ROUTER_ID: "{{ item.ROUTER_ID }}"
      AS_NUMBER: "{{ AS_NUMBER }} "
      IS_RR: "false"
      IS_INJECTOR: "false"
      RR_ADDRESS1: "{{ RR_ADDRESS1 }}"
      RR_ADDRESS2: "{{ RR_ADDRESS2 }}"
      TRANSLATION_PREFIX: "{{ TRANSLATION_PREFIX }}"
  loop: "{{ CONTAINERS }}"
  when: STOPPED

- name: wait docker log
  pause:
    seconds: "5"

- name: get docker log
  fetch:
    src: /home/ubuntu/docker-log.txt
    dest: "./backup/pod/docker-log.txt"
    flat: yes

- name: delete old docker log
  file:
    path: /home/ubuntu/docker-log.txt
    state: absent
