- name: install python-docker
  pip:
    name: docker
    executable: pip3

- name: Create bridge network for Containers
  docker_network:
    name: service_net
    enable_ipv6: yes
    ipam_config:
      - subnet: "{{ POD_NETWORK }}{{ POD_PREFIX }}"
    state: present

- name: git clone new version
  become: no
  git:
    repo: "git@github.com:yas-nyan/siit-client-docker.git"
    dest: /home/ubuntu/siit-client-docker
    version: origin/master
    accept_hostkey: yes
    force: yes
- name: create image
  docker_image:
    build:
      path: /home/ubuntu/siit-client-docker
    name: siit_gobgpd
    source: build
    state: present
    force_source: yes

- name: crate injector containers with paused state
  docker_container:
    name: "{{ item.NAME }}"
    image: siit_gobgpd
    state: started
    paused: yes
    auto_remove: yes
    networks:
      - ipv6_address: "{{ POD_NETWORK }}{{ item.ROUTER_ID }}"
        name: service_net
    env:
      ROUTER_ID: "{{ item.ROUTER_ID }}"
      AS_NUMBER: "{{ AS_NUMBER }} "
      IS_RR: "false"
      IS_INJECTOR: "true"
      INJECT_COUNT: "{{ item.INJECT_COUNT }}"
      RR_ADDRESS1: "{{ RR_ADDRESS1 }}"
      RR_ADDRESS2: "{{ RR_ADDRESS2 }}"
      TRANSLATION_PREFIX: "{{ TRANSLATION_PREFIX }}"
  loop: "{{ INJECTORS }}"

- name: Create Containers
  docker_container:
    name: "{{ item.NAME }}"
    image: siit_gobgpd
    state: started
    auto_remove: yes
    networks:
      - ipv6_address: "{{ POD_NETWORK }}{{ item.ROUTER_ID }}"
        name: service_net
    env:
      ROUTER_ID: "{{ item.ROUTER_ID }}"
      AS_NUMBER: "{{ AS_NUMBER }} "
      IS_RR: "false"
      IS_INJECTOR: "false"
      RR_ADDRESS1: "{{ RR_ADDRESS1 }}"
      RR_ADDRESS2: "{{ RR_ADDRESS2 }}"
      TRANSLATION_PREFIX: "{{ TRANSLATION_PREFIX }}"
  loop: "{{ SERVERS }}"
