- name: config | Configuring daemons
  template:
    backup: yes
    src: daemons.j2
    dest: /etc/frr/daemons
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: config | Configuring frr.conf
  template:
    backup: yes
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - restart frr
    - start frr
