POD_NETWORK: '2001:200:0:8831:1::'
POD_PREFIX: /80
SERVERS:
- NAME: pod1-0
  ROUTER_ID: 100.64.0.1
- NAME: pod1-2
  ROUTER_ID: 100.64.0.3
- NAME: pod1-4
  ROUTER_ID: 100.64.0.5
- NAME: pod1-6
  ROUTER_ID: 100.64.0.7
- NAME: pod1-8
  ROUTER_ID: 100.64.0.9
