POD_NETWORK: "2001:200:0:8831:2::"
POD_PREFIX: "/80"
SERVERS:
  - NAME: server2-0
    ROUTER-ID: 100.64.2.0
  - NAME: server2-1
    ROUTER-ID: 100.64.2.1
  - NAME: server2-2
    ROUTER-ID: 100.64.2.2
  - NAME: server2-3
    ROUTER-ID: 100.64.2.3
  - NAME: server2-4
    ROUTER-ID: 100.64.2.4
  - NAME: server2-5
    ROUTER-ID: 100.64.2.5
  - NAME: server2-6
    ROUTER-ID: 100.64.2.6
  - NAME: server2-7
    ROUTER-ID: 100.64.2.7
  - NAME: server2-8
    ROUTER-ID: 100.64.2.8
  - NAME: server2-9
    ROUTER-ID: 100.64.2.9
  - NAME: server2-10
    ROUTER-ID: 100.64.2.10
  - NAME: server2-11
    ROUTER-ID: 100.64.2.11
  - NAME: server2-12
    ROUTER-ID: 100.64.2.12
  - NAME: server2-13
    ROUTER-ID: 100.64.2.13
  - NAME: server2-14
    ROUTER-ID: 100.64.2.14
  - NAME: server2-15
    ROUTER-ID: 100.64.2.15
  - NAME: server2-16
    ROUTER-ID: 100.64.2.16
  - NAME: server2-17
    ROUTER-ID: 100.64.2.17
  - NAME: server2-18
    ROUTER-ID: 100.64.2.18
  - NAME: server2-19
    ROUTER-ID: 100.64.2.19
  - NAME: server2-20
    ROUTER-ID: 100.64.2.20
  - NAME: server2-21
    ROUTER-ID: 100.64.2.21
  - NAME: server2-22
    ROUTER-ID: 100.64.2.22
  - NAME: server2-23
    ROUTER-ID: 100.64.2.23
  - NAME: server2-24
    ROUTER-ID: 100.64.2.24
  - NAME: server2-25
    ROUTER-ID: 100.64.2.25
  - NAME: server2-26
    ROUTER-ID: 100.64.2.26
  - NAME: server2-27
    ROUTER-ID: 100.64.2.27
  - NAME: server2-28
    ROUTER-ID: 100.64.2.28
  - NAME: server2-29
    ROUTER-ID: 100.64.2.29
  - NAME: server2-30
    ROUTER-ID: 100.64.2.30
  - NAME: server2-31
    ROUTER-ID: 100.64.2.31
  - NAME: server2-32
    ROUTER-ID: 100.64.2.32
  - NAME: server2-33
    ROUTER-ID: 100.64.2.33
  - NAME: server2-34
    ROUTER-ID: 100.64.2.34
  - NAME: server2-35
    ROUTER-ID: 100.64.2.35
  - NAME: server2-36
    ROUTER-ID: 100.64.2.36
  - NAME: server2-37
    ROUTER-ID: 100.64.2.37
  - NAME: server2-38
    ROUTER-ID: 100.64.2.38
  - NAME: server2-39
    ROUTER-ID: 100.64.2.39
  - NAME: server2-40
    ROUTER-ID: 100.64.2.40
  - NAME: server2-41
    ROUTER-ID: 100.64.2.41
  - NAME: server2-42
    ROUTER-ID: 100.64.2.42
  - NAME: server2-43
    ROUTER-ID: 100.64.2.43
  - NAME: server2-44
    ROUTER-ID: 100.64.2.44
  - NAME: server2-45
    ROUTER-ID: 100.64.2.45
  - NAME: server2-46
    ROUTER-ID: 100.64.2.46
  - NAME: server2-47
    ROUTER-ID: 100.64.2.47
  - NAME: server2-48
    ROUTER-ID: 100.64.2.48
  - NAME: server2-49
    ROUTER-ID: 100.64.2.49
  - NAME: server2-50
    ROUTER-ID: 100.64.2.50
  - NAME: server2-51
    ROUTER-ID: 100.64.2.51
  - NAME: server2-52
    ROUTER-ID: 100.64.2.52
  - NAME: server2-53
    ROUTER-ID: 100.64.2.53
  - NAME: server2-54
    ROUTER-ID: 100.64.2.54
  - NAME: server2-55
    ROUTER-ID: 100.64.2.55
  - NAME: server2-56
    ROUTER-ID: 100.64.2.56
  - NAME: server2-57
    ROUTER-ID: 100.64.2.57
  - NAME: server2-58
    ROUTER-ID: 100.64.2.58
  - NAME: server2-59
    ROUTER-ID: 100.64.2.59
  - NAME: server2-60
    ROUTER-ID: 100.64.2.60
  - NAME: server2-61
    ROUTER-ID: 100.64.2.61
  - NAME: server2-62
    ROUTER-ID: 100.64.2.62
  - NAME: server2-63
    ROUTER-ID: 100.64.2.63
  - NAME: server2-64
    ROUTER-ID: 100.64.2.64
  - NAME: server2-65
    ROUTER-ID: 100.64.2.65
  - NAME: server2-66
    ROUTER-ID: 100.64.2.66
  - NAME: server2-67
    ROUTER-ID: 100.64.2.67
  - NAME: server2-68
    ROUTER-ID: 100.64.2.68
  - NAME: server2-69
    ROUTER-ID: 100.64.2.69
  - NAME: server2-70
    ROUTER-ID: 100.64.2.70
  - NAME: server2-71
    ROUTER-ID: 100.64.2.71
  - NAME: server2-72
    ROUTER-ID: 100.64.2.72
  - NAME: server2-73
    ROUTER-ID: 100.64.2.73
  - NAME: server2-74
    ROUTER-ID: 100.64.2.74
  - NAME: server2-75
    ROUTER-ID: 100.64.2.75
  - NAME: server2-76
    ROUTER-ID: 100.64.2.76
  - NAME: server2-77
    ROUTER-ID: 100.64.2.77
  - NAME: server2-78
    ROUTER-ID: 100.64.2.78
  - NAME: server2-79
    ROUTER-ID: 100.64.2.79
  - NAME: server2-80
    ROUTER-ID: 100.64.2.80
  - NAME: server2-81
    ROUTER-ID: 100.64.2.81
  - NAME: server2-82
    ROUTER-ID: 100.64.2.82
  - NAME: server2-83
    ROUTER-ID: 100.64.2.83
  - NAME: server2-84
    ROUTER-ID: 100.64.2.84
  - NAME: server2-85
    ROUTER-ID: 100.64.2.85
  - NAME: server2-86
    ROUTER-ID: 100.64.2.86
  - NAME: server2-87
    ROUTER-ID: 100.64.2.87
  - NAME: server2-88
    ROUTER-ID: 100.64.2.88
  - NAME: server2-89
    ROUTER-ID: 100.64.2.89
  - NAME: server2-90
    ROUTER-ID: 100.64.2.90
  - NAME: server2-91
    ROUTER-ID: 100.64.2.91
  - NAME: server2-92
    ROUTER-ID: 100.64.2.92
  - NAME: server2-93
    ROUTER-ID: 100.64.2.93
  - NAME: server2-94
    ROUTER-ID: 100.64.2.94
  - NAME: server2-95
    ROUTER-ID: 100.64.2.95
  - NAME: server2-96
    ROUTER-ID: 100.64.2.96
  - NAME: server2-97
    ROUTER-ID: 100.64.2.97
  - NAME: server2-98
    ROUTER-ID: 100.64.2.98
  - NAME: server2-99
    ROUTER-ID: 100.64.2.99
  - NAME: server2-100
    ROUTER-ID: 100.64.2.100
  - NAME: server2-101
    ROUTER-ID: 100.64.2.101
  - NAME: server2-102
    ROUTER-ID: 100.64.2.102
  - NAME: server2-103
    ROUTER-ID: 100.64.2.103
  - NAME: server2-104
    ROUTER-ID: 100.64.2.104
  - NAME: server2-105
    ROUTER-ID: 100.64.2.105
  - NAME: server2-106
    ROUTER-ID: 100.64.2.106
  - NAME: server2-107
    ROUTER-ID: 100.64.2.107
  - NAME: server2-108
    ROUTER-ID: 100.64.2.108
  - NAME: server2-109
    ROUTER-ID: 100.64.2.109
  - NAME: server2-110
    ROUTER-ID: 100.64.2.110
  - NAME: server2-111
    ROUTER-ID: 100.64.2.111
  - NAME: server2-112
    ROUTER-ID: 100.64.2.112
  - NAME: server2-113
    ROUTER-ID: 100.64.2.113
  - NAME: server2-114
    ROUTER-ID: 100.64.2.114
  - NAME: server2-115
    ROUTER-ID: 100.64.2.115
  - NAME: server2-116
    ROUTER-ID: 100.64.2.116
  - NAME: server2-117
    ROUTER-ID: 100.64.2.117
  - NAME: server2-118
    ROUTER-ID: 100.64.2.118
  - NAME: server2-119
    ROUTER-ID: 100.64.2.119
  - NAME: server2-120
    ROUTER-ID: 100.64.2.120
  - NAME: server2-121
    ROUTER-ID: 100.64.2.121
  - NAME: server2-122
    ROUTER-ID: 100.64.2.122
  - NAME: server2-123
    ROUTER-ID: 100.64.2.123
  - NAME: server2-124
    ROUTER-ID: 100.64.2.124
  - NAME: server2-125
    ROUTER-ID: 100.64.2.125
  - NAME: server2-126
    ROUTER-ID: 100.64.2.126
  - NAME: server2-127
    ROUTER-ID: 100.64.2.127
  - NAME: server2-128
    ROUTER-ID: 100.64.2.128
  - NAME: server2-129
    ROUTER-ID: 100.64.2.129
  - NAME: server2-130
    ROUTER-ID: 100.64.2.130
  - NAME: server2-131
    ROUTER-ID: 100.64.2.131
  - NAME: server2-132
    ROUTER-ID: 100.64.2.132
  - NAME: server2-133
    ROUTER-ID: 100.64.2.133
  - NAME: server2-134
    ROUTER-ID: 100.64.2.134
  - NAME: server2-135
    ROUTER-ID: 100.64.2.135
  - NAME: server2-136
    ROUTER-ID: 100.64.2.136
  - NAME: server2-137
    ROUTER-ID: 100.64.2.137
  - NAME: server2-138
    ROUTER-ID: 100.64.2.138
  - NAME: server2-139
    ROUTER-ID: 100.64.2.139
  - NAME: server2-140
    ROUTER-ID: 100.64.2.140
  - NAME: server2-141
    ROUTER-ID: 100.64.2.141
  - NAME: server2-142
    ROUTER-ID: 100.64.2.142
  - NAME: server2-143
    ROUTER-ID: 100.64.2.143
  - NAME: server2-144
    ROUTER-ID: 100.64.2.144
  - NAME: server2-145
    ROUTER-ID: 100.64.2.145
  - NAME: server2-146
    ROUTER-ID: 100.64.2.146
  - NAME: server2-147
    ROUTER-ID: 100.64.2.147
  - NAME: server2-148
    ROUTER-ID: 100.64.2.148
  - NAME: server2-149
    ROUTER-ID: 100.64.2.149
  - NAME: server2-150
    ROUTER-ID: 100.64.2.150
  - NAME: server2-151
    ROUTER-ID: 100.64.2.151
  - NAME: server2-152
    ROUTER-ID: 100.64.2.152
  - NAME: server2-153
    ROUTER-ID: 100.64.2.153
  - NAME: server2-154
    ROUTER-ID: 100.64.2.154
  - NAME: server2-155
    ROUTER-ID: 100.64.2.155
  - NAME: server2-156
    ROUTER-ID: 100.64.2.156
  - NAME: server2-157
    ROUTER-ID: 100.64.2.157
  - NAME: server2-158
    ROUTER-ID: 100.64.2.158
  - NAME: server2-159
    ROUTER-ID: 100.64.2.159
  - NAME: server2-160
    ROUTER-ID: 100.64.2.160
  - NAME: server2-161
    ROUTER-ID: 100.64.2.161
  - NAME: server2-162
    ROUTER-ID: 100.64.2.162
  - NAME: server2-163
    ROUTER-ID: 100.64.2.163
  - NAME: server2-164
    ROUTER-ID: 100.64.2.164
  - NAME: server2-165
    ROUTER-ID: 100.64.2.165
  - NAME: server2-166
    ROUTER-ID: 100.64.2.166
  - NAME: server2-167
    ROUTER-ID: 100.64.2.167
  - NAME: server2-168
    ROUTER-ID: 100.64.2.168
  - NAME: server2-169
    ROUTER-ID: 100.64.2.169
  - NAME: server2-170
    ROUTER-ID: 100.64.2.170
  - NAME: server2-171
    ROUTER-ID: 100.64.2.171
  - NAME: server2-172
    ROUTER-ID: 100.64.2.172
  - NAME: server2-173
    ROUTER-ID: 100.64.2.173
  - NAME: server2-174
    ROUTER-ID: 100.64.2.174
  - NAME: server2-175
    ROUTER-ID: 100.64.2.175
  - NAME: server2-176
    ROUTER-ID: 100.64.2.176
  - NAME: server2-177
    ROUTER-ID: 100.64.2.177
  - NAME: server2-178
    ROUTER-ID: 100.64.2.178
  - NAME: server2-179
    ROUTER-ID: 100.64.2.179
  - NAME: server2-180
    ROUTER-ID: 100.64.2.180
  - NAME: server2-181
    ROUTER-ID: 100.64.2.181
  - NAME: server2-182
    ROUTER-ID: 100.64.2.182
  - NAME: server2-183
    ROUTER-ID: 100.64.2.183
  - NAME: server2-184
    ROUTER-ID: 100.64.2.184
  - NAME: server2-185
    ROUTER-ID: 100.64.2.185
  - NAME: server2-186
    ROUTER-ID: 100.64.2.186
  - NAME: server2-187
    ROUTER-ID: 100.64.2.187
  - NAME: server2-188
    ROUTER-ID: 100.64.2.188
  - NAME: server2-189
    ROUTER-ID: 100.64.2.189
  - NAME: server2-190
    ROUTER-ID: 100.64.2.190
  - NAME: server2-191
    ROUTER-ID: 100.64.2.191
  - NAME: server2-192
    ROUTER-ID: 100.64.2.192
  - NAME: server2-193
    ROUTER-ID: 100.64.2.193
  - NAME: server2-194
    ROUTER-ID: 100.64.2.194
  - NAME: server2-195
    ROUTER-ID: 100.64.2.195
  - NAME: server2-196
    ROUTER-ID: 100.64.2.196
  - NAME: server2-197
    ROUTER-ID: 100.64.2.197
  - NAME: server2-198
    ROUTER-ID: 100.64.2.198
  - NAME: server2-199
    ROUTER-ID: 100.64.2.199
  - NAME: server2-200
    ROUTER-ID: 100.64.2.200
  - NAME: server2-201
    ROUTER-ID: 100.64.2.201
  - NAME: server2-202
    ROUTER-ID: 100.64.2.202
  - NAME: server2-203
    ROUTER-ID: 100.64.2.203
  - NAME: server2-204
    ROUTER-ID: 100.64.2.204
  - NAME: server2-205
    ROUTER-ID: 100.64.2.205
  - NAME: server2-206
    ROUTER-ID: 100.64.2.206
  - NAME: server2-207
    ROUTER-ID: 100.64.2.207
  - NAME: server2-208
    ROUTER-ID: 100.64.2.208
  - NAME: server2-209
    ROUTER-ID: 100.64.2.209
  - NAME: server2-210
    ROUTER-ID: 100.64.2.210
  - NAME: server2-211
    ROUTER-ID: 100.64.2.211
  - NAME: server2-212
    ROUTER-ID: 100.64.2.212
  - NAME: server2-213
    ROUTER-ID: 100.64.2.213
  - NAME: server2-214
    ROUTER-ID: 100.64.2.214
  - NAME: server2-215
    ROUTER-ID: 100.64.2.215
  - NAME: server2-216
    ROUTER-ID: 100.64.2.216
  - NAME: server2-217
    ROUTER-ID: 100.64.2.217
  - NAME: server2-218
    ROUTER-ID: 100.64.2.218
  - NAME: server2-219
    ROUTER-ID: 100.64.2.219
  - NAME: server2-220
    ROUTER-ID: 100.64.2.220
  - NAME: server2-221
    ROUTER-ID: 100.64.2.221
  - NAME: server2-222
    ROUTER-ID: 100.64.2.222
  - NAME: server2-223
    ROUTER-ID: 100.64.2.223
  - NAME: server2-224
    ROUTER-ID: 100.64.2.224
  - NAME: server2-225
    ROUTER-ID: 100.64.2.225
  - NAME: server2-226
    ROUTER-ID: 100.64.2.226
  - NAME: server2-227
    ROUTER-ID: 100.64.2.227
  - NAME: server2-228
    ROUTER-ID: 100.64.2.228
  - NAME: server2-229
    ROUTER-ID: 100.64.2.229
  - NAME: server2-230
    ROUTER-ID: 100.64.2.230
  - NAME: server2-231
    ROUTER-ID: 100.64.2.231
  - NAME: server2-232
    ROUTER-ID: 100.64.2.232
  - NAME: server2-233
    ROUTER-ID: 100.64.2.233
  - NAME: server2-234
    ROUTER-ID: 100.64.2.234
  - NAME: server2-235
    ROUTER-ID: 100.64.2.235
  - NAME: server2-236
    ROUTER-ID: 100.64.2.236
  - NAME: server2-237
    ROUTER-ID: 100.64.2.237
  - NAME: server2-238
    ROUTER-ID: 100.64.2.238
  - NAME: server2-239
    ROUTER-ID: 100.64.2.239
  - NAME: server2-240
    ROUTER-ID: 100.64.2.240
  - NAME: server2-241
    ROUTER-ID: 100.64.2.241
  - NAME: server2-242
    ROUTER-ID: 100.64.2.242
  - NAME: server2-243
    ROUTER-ID: 100.64.2.243
  - NAME: server2-244
    ROUTER-ID: 100.64.2.244
  - NAME: server2-245
    ROUTER-ID: 100.64.2.245
  - NAME: server2-246
    ROUTER-ID: 100.64.2.246
  - NAME: server2-247
    ROUTER-ID: 100.64.2.247
  - NAME: server2-248
    ROUTER-ID: 100.64.2.248
  - NAME: server2-249
    ROUTER-ID: 100.64.2.249
  - NAME: server2-250
    ROUTER-ID: 100.64.2.250
  - NAME: server2-251
    ROUTER-ID: 100.64.2.251
  - NAME: server2-252
    ROUTER-ID: 100.64.2.252
  - NAME: server2-253
    ROUTER-ID: 100.64.2.253
  - NAME: server2-254
    ROUTER-ID: 100.64.2.254
  - NAME: server2-255
    ROUTER-ID: 100.64.2.255
