- name: calc convergence time
  command: "python3 {{role_path}}/test/convergence.py {{ COMPLETE_EAMT_COUNT }}"
  register: result

- name: show result
  debug:
    msg: "{{ result['stdout'] }}"

- name: export result to file
  lineinfile:
    line: "{{ lookup('pipe','date +%Y/%m/%d/%H:%M:%S') }},{{ result['stdout'] }}"
    dest: "{{ LOG_PATH }}"
    create: yes
  when: LOG_PATH is defined
