- name: Get running processes list from remote host
  ignore_errors: yes
  shell: "ps -few | grep siit-manipulatord | awk '{print $2}'"
  register: running_processes

- name: show runnning process
  debug:
    var: running_processes

- name: Kill running processes
  ignore_errors: yes
  shell: "kill {{ item }}"
  loop: "{{ running_processes.stdout_lines }}"

- name: force reread
  shell: supervisorctl reread
- name: force reload
  shell: supervisorctl reload
